Remove storage address from head model
Substra/substra-chaincode pull request #84
Opened 2020-02-03 17:24 UTC by Kelvin-M

Backend PR : https://github.com/SubstraFoundation/substra-backend/pull/139

2020-02-03 17:25 UTC, Kelvin-M commented
@thibaultrobert  It could be cleaner to have a `Hash` Structure than a `HashDress` with storage address not mandatory

2020-02-04 15:18 UTC, jmorel approved these changes
Tested through https://github.com/SubstraFoundation/substra-tests/pull/71/files and working as expected!

2020-02-06 09:19 UTC, thibaultrobert approved these changes

2020-02-06 09:23 UTC, thibaultrobert requested changes

2020-02-06 09:23 UTC, thibaultrobert commented on chaincode/input.go
>  }
Not the right way

2020-02-06 10:08 UTC, thibaultrobert approved these changes

2020-02-06 15:19 UTC, merged